### ISSUE TITLE
UART Level Shifter?

### ISSUE THREAD

**Issue by simme** [mcore1976/sim7000gpstracker#1]
Hey,

Thanks for this project. Very helpful as a reference as I'm learning to do this myself :)

I'm just curious, according to the [SIM7000 User Manual](https://fccid.io/2AJYU-SIM7000G/User-Manual/User-Manual-4050964.pdf) the UART interface of the SIM7000 operates at 1.8V, while as far as I can tell the ATMEGA is running at 3.3V. Did you not have to use a level shifter between them to get UART to work properly? Or do you know if the breakout board perhaps has that built in?

Best,
Simon

**Comment by mcore1976** [comment]
Hi,I havent use any level shifter to interoperate with SIM7000 board. It worked staight away. Also on tge board I cannot see any Zener diodes etc. so probably the chip accepts higher voltage levels and 3.3V is not a problem for it.cheersWysłano z mojego urządzenia Galaxy
-------- Oryginalna wiadomość --------Od: Simon Ljungberg <notifications@github.com> Data: 13.01.2021  09:24  (GMT+01:00) Do: mcore1976/sim7000gpstracker <sim7000gpstracker@noreply.github.com> DW: Subscribed <subscribed@noreply.github.com> Temat: [mcore1976/sim7000gpstracker] UART Level Shifter? (#1) 
Hey,
Thanks for this project. Very helpful as a reference as I'm learning to do this myself :)
I'm just curious, according to the SIM7000 User Manual the UART interface of the SIM7000 operates at 1.8V, while as far as I can tell the ATMEGA is running at 3.3V. Did you not have to use a level shifter between them to get UART to work properly? Or do you know if the breakout board perhaps has that built in?
Best,
Simon

**Comment by simme** [comment]
Thank you! :)
Perhaps I'm having some other issues then.

**Comment by simme** [comment]
I managed to get a hold of the documents for the breakout board (just emailed and-global). The user manual states that the UART on the BK is 3.3v! So they have the level shifter built in.

It also says that the BK wants 5-10 VCC (5.0 is recommended).

Just a FYI if you're interested :) Attaching the manual.

[BK-SIM7000 Board user manual V1.0.pdf](https://github.com/mcore1976/sim7000gpstracker/files/5817142/BK-SIM7000.Board.user.manual.V1.0.pdf)

**Comment by mcore1976** [comment]
thanks ! Wysłano z mojego urządzenia Galaxy
-------- Oryginalna wiadomość --------Od: Simon Ljungberg <notifications@github.com> Data: 14.01.2021  22:44  (GMT+01:00) Do: mcore1976/sim7000gpstracker <sim7000gpstracker@noreply.github.com> DW: Adam Loboda <adam.loboda@wp.pl>, Comment <comment@noreply.github.com> Temat: Re: [mcore1976/sim7000gpstracker] UART Level Shifter? (#1) 
I managed to get a hold of the documents for the breakout board (just emailed and-global). The user manual states that the UART on the BK is 3.3v! So they have the level shifter built in.
It also says that the BK wants 5-10 VCC (5.0 is recommended).
Just a FYI if you're interested :) Attaching the manual.
BK-SIM7000 Board user manual V1.0.pdf
